name: PR Build

on:
  push:
    branches: [ main ]
  pull_request:
  
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
        
    - name: Build
      run: dotnet run --projects tools\SpreadsheetIO.Tool.Build\LanceC.SpreadsheetIO.Tool.Build.csproj
